name: Build and push docker image #nom

on:
    push:
        branches:
            - master #la branche conernee dans Github
jobs:
    build:
        runs-on: ubuntu-latest #le syteme dans le serveur qui va executer
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to docker hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }} #les informations sont stockes dans le compte Github
                password: ${{ secrets.DOCKER_PASSWORD }} #token generated dans docker hub et stocke dans github

            - name: Build Docker image
              run: docker build -t haritsima/docker_with_cloud:latest . #ne pas oublier le point

            - name: Push Docker image
              run: docker push haritsima/docker_with_cloud

    deploy: 
      runs-on: self-hosted
      needs: build
      steps:
        - name: pull image
          run: docker pull haritsima/docker_with_cloud:latest

        - name: stop old container
          run: docker stop docker_with_cloud || true

        - name: remove old container
          run: docker rm docker_with_cloud || true

        - name: run new container
          run: docker run -d -p 8080:80 --name docker_with_cloud haritsima/docker_with_cloud